### ISSUE TITLE
Functor and Applicative instance for Map

### ISSUE THREAD

**Issue by adavydow** [uncomplicate/fluokitten#19]
1. Variadic fmap for maps sometimes fails with ArityException:
    `(fmap subs {:a "abc" :b "cde"} {:a 1 :c 2})`
2. fapply for maps sometimes return result of incorrect type:
    `(fapply {:a (partial subs "abc") :b (partial subs "abc")} {:a 1 :c 2})`
      - expected: value of type `(Map Keyword String)` (first parameter is of type `(Map Keyword (IFn [Int -> String]))`, second parameter is of type `(Map Keyword Int)`, so we fapply `(Applicative (IFn [Int -> String]))` to `(Applicative Int)` and shall obtain `(Applicative String)` (type annotation of typed clojure is used)).
      - result: `{:a "bc" :c 2}` - Heterogeneous map.
3. Strange behaviour for maps containing nils as keys:
    `(fapply {:a inc nil dec} {:a 1 :b 2}) = {:a 2 :b 1}`
    while
    `(fapply {:a inc :c dec} {:a 1 :b 2}) = {:a 2 : b 2}`

In fact both fapply and variadic fmap for maps works only in case of maps of identical keys, or functions with variadic homogeneus parameters.

**Comment by blueberry** [comment]
1. It works as it should. subs requires 2 arguments while for keys :b and :c only one is provided. Handling different arities is a matter of subs, not fmap. Alternatively, fapply can cope with this problem because it can give a context to subs.

2. What you mean incorrect type? It receives maps and returns maps.

3. It is not a strange behavior. nil is a key for "default" function that is applied when the function with a processed key is not supplied.
